[package]
name = "korea_investment_rs"
version = "0.1.1"
edition = "2024"
description = "Korea Investment & Securities Open API"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }


[dependencies.dotenv]
version = "0.15.0"
optional = true


[features]
ex = ["dotenv"]
