[package]
name = "korea_investment_rs"
version = "0.1.0"
edition = "2024"
description = "A fun game where you guess what number the computer has chosen."
license = "MIT OR Apache-2.0"

[dependencies]
reqwest = "0.12.15"
